export const turnosMarzo = [
    { dia: 1, nombre: 'Lunes', farmacia: 'Cicconi' },
    { dia: 2, nombre: 'Martes', farmacia: 'Cululo' },
    { dia: 3, nombre: 'Miércoles', farmacia: 'Nencionni' },
    { dia: 4, nombre: 'Jueves', farmacia: 'Carestia' },
    { dia: 5, nombre: 'Viernes', farmacia: 'Arias' },
    { dia: 6, nombre: 'Lunes', farmacia: 'Cicconi' },
    { dia: 7, nombre: 'Lunes', farmacia: 'Carestia' },
    { dia: 8, nombre: 'Lunes', farmacia: 'Arias' },
    { dia: 9, nombre: 'Martes', farmacia: 'Cululo' },
    { dia: 10, nombre: 'Miércoles', farmacia: 'Nencionni'},
    { dia: 11, nombre: 'Jueves', farmacia: 'Carestia' },
    { dia: 12, nombre: 'Viernes', farmacia: 'Arias' },
    { dia: 13, nombre: 'Viernes', farmacia: 'Arias' },
    { dia: 14, nombre: 'Sábado', farmacia: 'Cicconi' },
    { dia: 15, nombre: 'Domingo', farmacia: 'Cululo' },
    { dia: 16, nombre: 'Lunes', farmacia: 'Nencionni' },
    { dia: 17, nombre: 'Martes', farmacia: 'Carestia' },
    { dia: 18, nombre: 'Miércoles', farmacia: 'Arias' },
    { dia: 19, nombre: 'Jueves', farmacia: 'Cicconi' },
    { dia: 20, nombre: 'Viernes', farmacia: 'Cululo' },
    { dia: 21, nombre: 'Sábado', farmacia: 'Nencionni' },
    { dia: 22, nombre: 'Domingo', farmacia: 'Carestia' },
    { dia: 23, nombre: 'Lunes', farmacia: 'Arias' },
    { dia: 24, nombre: 'Martes', farmacia: 'Cicconi' },
    { dia: 25, nombre: 'Miércoles', farmacia: 'Cululo' },
    { dia: 26, nombre: 'Jueves', farmacia: 'Nencionni' },
    { dia: 27, nombre: 'Viernes', farmacia: 'Carestia' },
    { dia: 28, nombre: 'Sábado', farmacia: 'Arias' },
    { dia: 29, nombre: 'Lunes', farmacia: 'Cicconi' },
    { dia: 30, nombre: 'Martes', farmacia: 'Cululo' },
    { dia: 31, nombre: 'Miércoles', farmacia: 'Nencionni' },
  ];